version: '3.3'

networks:
  default:
    external:
      name: br-docker

services:

  fpm:
    volumes:
      - '/var/www/html:/var/www/html'
      - '/root/.ssh:/root/.ssh'
    network_mode: br-docker
    container_name: dphp
    image: 'akuznetsov/fpm:v1'

  mariadb:
      environment:
        - MYSQL_ROOT_PASSWORD=7bn8vrt
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
      volumes:
        - '/var/lib/mariadb/data/:/var/lib/mariadb/data/'
      ports:
        - '127.0.0.1:3306:3306'
      network_mode: br-docker
      container_name: dmariadb
      image: mariadb:latest

  nginx:
    volumes:
      - '/etc/nginx/site_enabled:/etc/nginx/conf.d'
      - '/var/www/html:/var/www/html'
    network_mode: br-docker
    container_name: dnginx
    image: nginx:latest
    environment:
      - VIRTUAL_HOST=thesigns.ru
      - LETSENCRYPT_HOST=thesigns.ru
      - LETSENCRYPT_EMAIL=admin@thesigns.ru
