version: '3.3'

networks:
  default:
    external:
      name: br-docker

services:

  #  nginx-proxy container redirects traffic depending on which host the client is accessing.
  #  Let's say on port 443, several containers will be available.

  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/www/html:/var/www/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

#  nginx-proxy-companion automatically obtains or renews a certificate.

  nginx-proxy-letsencrypt:
    container_name: nginx-proxy-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy

volumes:
  certs:
  vhost.d:
  html:
